In [30]:
#step1: we  have to import the dataset to the colab note book.
import pandas as pd #pd is an instance of pandas
df=pd.read_csv('Data.csv')#df is a variable,read_csv is a predefined function from pandas package

In [31]:
type(df)

pandas.core.frame.DataFrame

In [32]:
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [33]:
#step2: grouping the input columns and output columns
x=df.iloc[:,:3]

In [34]:
x

Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [35]:
y=df.iloc[:,3:5]

In [36]:
y

Purchased
0        No
1       Yes
2        No
3        No
4       Yes
5       Yes
6        No
7       Yes
8        No
9       Yes

In [37]:
x=x.values

In [38]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [39]:
y=y.values

In [40]:
y

array([['No'],
       ['Yes'],
       ['No'],
       ['No'],
       ['Yes'],
       ['Yes'],
       ['No'],
       ['Yes'],
       ['No'],
       ['Yes']], dtype=object)

In [41]:
#step3: Handling the missing data or values
#scenario-1:
#scenario-2:
#scenario-3:

import numpy as np
from sklearn.impute import SimpleImputer

imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit(x[:,1:3])
x[:,1:3]=imputer.transform(x[:,1:3])

In [42]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [43]:
#step4: Handling the catogorial data
#which coverts the text data into numeric data.
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

#Alexa-0,0,1

ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')#endcoder is a method which converts text to binary
x=ct.fit_transform(x)

In [44]:
x

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [45]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)


/usr/local/lib/python3.11/dist-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [46]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [47]:
#step5: Split the data into training and testing data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [48]:
x_train

array([[0.0, 0.0, 1.0, 27.0, 48000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [1.0, 0.0, 0.0, 44.0, 72000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0]], dtype=object)

In [49]:
x_test

array([[0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 35.0, 58000.0]], dtype=object)

In [50]:
y_train

array([1, 1, 0, 0, 1, 0, 1, 0])

In [51]:
y_test

array([0, 1])

In [52]:
#step6:feature scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train[:,3:]=sc.fit_transform(x_train[:,3:])
x_test[:,3:]=sc.transform(x_test[:,3:])

In [53]:
x_train

array([[0.0, 0.0, 1.0, -1.6981511422696691, -1.4294371083848152],
       [1.0, 0.0, 0.0, -0.13263408409532615, 0.49713428498506423],
       [0.0, 0.0, 1.0, 0.023917621722108144, -0.1112566813422661],
       [1.0, 0.0, 0.0, 0.963227856626714, 1.0041267569245063],
       [1.0, 0.0, 0.0, 1.5894346798964512, 1.713916217639725],
       [0.0, 1.0, 0.0, -1.2284960248173662, -0.8210461420574848],
       [0.0, 1.0, 0.0, 0.33702103335697675, 0.1704058030685353],
       [0.0, 0.0, 1.0, 0.14568005958011274, -1.0238431308332616]],
      dtype=object)

In [54]:
x_test

array([[0.0, 1.0, 0.0, 1.9025380915313197, 2.1195101951912787],
       [1.0, 0.0, 0.0, -0.4457374957301948, -0.41545216450593125]],
      dtype=object)

In [55]:
#machine learning
#1. supervisioned learning-when we have labled data,
# and the model tasks are classification or prediction
#2. unsupervised learning-unlabled data, model remembers the patterns
#we can perform prediction also.
#3. reinforcement learning-trail and error method,model learns from failures

In [56]:
#logistic regression algorithm=(classifications)
#when model performs classification we have to apply logistic algorithm
#linear regression algorithm: when model performs prediction tasks we have to apply linear algorithm
#step7: appling algorithm to the data for model training
from sklearn.linear_model import LogisticRegression
classifir=LogisticRegression()
classifir.fit(x_train,y_train)

LogisticRegression()

In [57]:
y_pred=classifir.predict(x_test)

In [58]:
y_pred

array([1, 1])